### PR TITLE
Added integration test

### LINKED ISSUE #4: Integration test
I will add Integration testing in the plugin as well as an example.

### PR DESCRIPTION
**Pull request by Abhishek01039**
fixes https://github.com/beximo/onboarding_screen/issues/4

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @woinbo ,
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
To run integration test.
Go to `example` tab and run this command ```flutter drive 
  --driver=test_driver/integration_test.dart 
  --target=integration_test/app_test.dart```

**Comment by Abhishek01039** [comment]
There is not any CI yet.

**Comment by woinbo** [comment]
> There is not any CI yet.

I implemented CI in the different branch so that any thing goes wrong it won't affect the master branch.

**Comment by woinbo** [comment]
> To run integration test.
> Go to `example` tab and run this command `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart`

While running this command, showing this error `Test file not found: test_driver/integration_test.dart`

**Comment by Abhishek01039** [comment]
Go to Example directory.

**Comment by Abhishek01039** [comment]
https://user-images.githubusercontent.com/56479665/107170285-f001a900-69e5-11eb-805a-31b88713d519.mov

This seems to work like this

**Comment by woinbo** [comment]
I cloned you PR and then run the same command but it's not working because one directory test_driver is missing in the example

**Comment by woinbo** [comment]
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54301/5YwMLr-ThJA=/
VMServiceFlutterDriver: Isolate found with number: 3088380654573971
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter ( 5912): 00:00 +0: testing `OnBoardingScreen` widget
VMServiceFlutterDriver: Connected to Flutter application.
I/GED     ( 5912): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
I/flutter ( 5912): (The following exception is now available via WidgetTester.takeException:)
I/flutter ( 5912): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 5912): The following TestFailure object was thrown running a test:
I/flutter ( 5912):   Expected: exactly one matching node in the widget tree
I/flutter ( 5912):   Actual: _KeyFinder:<zero widgets with key [<'get_started'>] (ignoring offstage widgets)>
I/flutter ( 5912):    Which: means none were found but one was expected
I/flutter ( 5912):
I/flutter ( 5912): When the exception was thrown, this was the stack:
I/flutter ( 5912): #4      main.<anonymous closure> (file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart:47:5)
I/flutter ( 5912): <asynchronous suspension>
I/flutter ( 5912): <asynchronous suspension>
I/flutter ( 5912): (elided one frame from package:stack_trace)
I/flutter ( 5912): ...
I/flutter ( 5912):
I/flutter ( 5912): This was caught by the test expectation on the following line:
I/flutter ( 5912):   file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart line 47
I/flutter ( 5912): The test description was:
I/flutter ( 5912):   testing `OnBoardingScreen` widget
I/flutter ( 5912): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5912): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception
is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter ( 5912): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 5912): The following TestFailure object was thrown running a test:
I/flutter ( 5912):   Expected: exactly one matching node in the widget tree
I/flutter ( 5912):   Actual: _KeyFinder:<zero widgets with key [<'get_started'>] (ignoring offstage widgets)>
I/flutter ( 5912):    Which: means none were found but one was expected
I/flutter ( 5912):
I/flutter ( 5912): When the exception was thrown, this was the stack:
I/flutter ( 5912): #4      main.<anonymous closure> (file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart:47:5)
I/flutter ( 5912): <asynchronous suspension>
I/flutter ( 5912): <asynchronous suspension>
I/flutter ( 5912): (elided one frame from package:stack_trace)
I/flutter ( 5912): ...
I/flutter ( 5912):
I/flutter ( 5912): This was caught by the test expectation on the following line:
I/flutter ( 5912):   file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart line 47
I/flutter ( 5912): The test description was:
I/flutter ( 5912):   testing `OnBoardingScreen` widget
I/flutter ( 5912): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5912): 00:19 +0: testing `OnBoardingScreen` widget [E]
I/flutter ( 5912):   Test failed. See exception logs above.
I/flutter ( 5912):   The test description was: testing `OnBoardingScreen` widget
I/flutter ( 5912):
I/flutter ( 5912): 00:19 +0 -1: (tearDownAll)
W/example.exampl( 5912): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking,
allowed)
I/flutter ( 5912): 00:19 +1 -1: Some tests failed.
Failure Details:
Failure in method: testing `OnBoardingScreen` widget
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _KeyFinder:<zero widgets with key [<'get_started'>]
(ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart:47:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Users/ankit/Desktop/onboarding_screen/example/integration_test/app_test.dart line 47
The test description was:
  testing `OnBoardingScreen` widget
═════════════════════════════════════════════════════════════════

end of failure 1



This is what I got when I tried to run integration test... `end of failure 1`, Please review the code @Abhishek01039 Thank you!

**Comment by Abhishek01039** [comment]
Seems like the `get_started` text can not be found by the tester.
can you please drop a video?

**Comment by woinbo** [comment]
https://user-images.githubusercontent.com/62764278/107187008-4cc38a80-6a0b-11eb-8195-1e78bc0c4965.mp4

video @Abhishek01039

**Comment by Abhishek01039** [comment]
image
This is working fine on my android device also...

**Comment by woinbo** [comment]
Let me once check it again and if I face any error further will inform you!!!

**Comment by woinbo** [comment]
LGTM, I will merge it into master...! Thank you @Abhishek01039

**Comment by Abhishek01039** [comment]
Now the test is running fine ? @woinbo

**Comment by woinbo** [comment]
> Now the test is running fine ? @woinbo 

I did some mistake , didn't checked out to integration_test branch 😅 sorry !!

**Pull request merged**
